# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run only modified test files

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run_on_modified_files:

    runs-on: ubuntu-latest

    name: "Job name: run modified test files only"

    steps:
    - uses: actions/checkout@v3

#    - name: Set up JDK 19
#      uses: actions/setup-java@v3
#      with:
#        java-version: '19'
#        distribution: 'temurin'
#        cache: maven

    - name: Print all modified test files
      run: |
        echo "List of files from git diff with awk: "
        echo $(git diff --name-only --diff-filter=ACMRT | grep src/test | grep -v -E "resources|pages" |  awk -F'/' '{print $NF}' | xargs | awk '{gsub(/ /,",")}1')

    # Example 1
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v37

      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      # with:
      #   since_last_remote_commit: true


    - name: List all modified (both added and changed) files
      id: find-modified-files
#        If changes in common files (outside of takehome/pages and takehome/tests) are present
#          => run all tests
#        else run only changed test files, substituting Page files with corresponding Test files
#        and removing duplicates
      run: |

        RUN_ALL=false
        TESTFILES_TO_RUN=
        for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
          if [[ ! "$file" =~ "takehome/tests/" ]] && [[ ! "$file" =~ "takehome/pages/" ]]; then
            echo "Changes in common files detected $file. Preparing to run all tests."
            RUN_ALL=true
            TESTFILES_TO_RUN=
            break
          elif [[ "$file" =~ "takehome/pages/" ]]; then
            echo "Found Page file $file"
            file=$(echo "$file" | sed 's/.*\/\(.*\)Page/\1Test/')
          fi
          TESTFILES_TO_RUN="$TESTFILES_TO_RUN","$file"
        done
        echo "RUN_ALL=$RUN_ALL" >> $GITHUB_OUTPUT
        echo "TESTFILES_TO_RUN=${TESTFILES_TO_RUN:1}" >> $GITHUB_OUTPUT
        

    - name: Run tests based on files that were updated
      id: run-tests-based-on-modified-files
      run: |
        if [[ ${{ steps.find-modified-files.outputs.RUN_ALL }} == true ]]; then
          echo "Running all tests"
          mvn -B package --file pom.xml
        else
          echo "Running selected tests ${{ steps.find-modified-files.outputs.TESTFILES_TO_RUN }} | sed 's/,/\n/'"
          mvn -B package --file pom.xml -Dtest="${{ steps.find-modified-files.outputs.TESTFILES_TO_RUN }}" test
        fi

#
#

#    - uses: browser-actions/setup-chrome@v1
#
#    - name: Build with Maven and Run only changed test files
#      run: mvn -B package --file pom.xml
#
